language: c

env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release

compiler: clang

install:
 - cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - cd Build
 - make
 - cd ..

script:
 - cd Build/Output
 - ./nominaltests
