language: cpp

env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release

compiler:
 - clang
 - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y valgrind

install:
 - cmake -H./ -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - cd build
 - make
 - cd ..

script:
 - cd build/output
 - ./nominaltests
 - valgrind ./nominaltests
