<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ns</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfn\s*(\w+\s*)?\([^\)]*\)(\s*\[[^\]]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\]</string>
	<key>name</key>
	<string>Nominal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#nominal_comment_doc_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nominal_comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nominal_self</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nominal_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nominal_raw_string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'([^\'\\]|\\(x\h{2}|u\{\h{1,6}\}|.))\'</string>
			<key>name</key>
			<string>string.quoted.single.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bself\b</string>
			<key>name</key>
			<string>variable.language.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|nil)\b</string>
			<key>name</key>
			<string>constant.language.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9][0-9_]*)|([0-9][0-9_]*(usize|u8|u16|u32|u64))|([0-9][0-9_]*(isize|i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0x[a-fA-F0-9_]+)|(0x[a-fA-F0-9_]+(usize|u8|u16|u32|u64))|(0x[a-fA-F0-9_]+(isize|i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.hex.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0b[01_]+)|(0b[01_]+(usize|u8|u16|u32|u64))|(0b[01_]+(isize|i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.binary.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9][0-9_]*(f32|f64|f))|([0-9][0-9_]*([eE][+-]=[0-9_]+))|([0-9][0-9_]*([eE][+-]=[0-9_]+)(f32|f64|f))|([0-9][0-9_]*\.[0-9_]+)|([0-9][0-9_]*\.[0-9_]+(f32|f64|f))|([0-9][0-9_]*\.[0-9_]+%([eE][+-]=[0-9_]+))|([0-9][0-9_]*\.[0-9_]+%([eE][+-]=[0-9_]+)(f32|f64|f)))\b</string>
			<key>name</key>
			<string>constant.numeric.float.source.nominal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.double-dash.source.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=&gt;)|(-&gt;)|[-:=*,!.+|%/&amp;~@&lt;&gt;;]</string>
			<key>name</key>
			<string>keyword.operator.nominal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\]|{|}|\(|\))</string>
			<key>name</key>
			<string>punctuation.definition.bracket.nominal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>nominal_comment_block</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>comment.block.source.nominal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nominal_comment_block</string>
				</dict>
			</array>
		</dict>
		<key>nominal_escaped_character</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|u\{\h{1,6}\}|.)</string>
			<key>name</key>
			<string>constant.character.escape.source.nominal</string>
		</dict>
		<key>nominal_raw_string</key>
		<dict>
			<key>begin</key>
			<string>r(#*)"</string>
			<key>end</key>
			<string>"(\1)</string>
			<key>name</key>
			<string>string.quoted.double.raw.source.nominal</string>
		</dict>
		<key>nominal_self</key>
		<dict>
			<key>match</key>
			<string>\bself\b</string>
			<key>name</key>
			<string>variable.language.source.nominal</string>
		</dict>
		<key>nominal_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.nominal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nominal_escaped_character</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nominal</string>
	<key>uuid</key>
	<string>4864a8a2-354b-11e5-a151-feff819cdc9f</string>
</dict>
</plist>
